### PR TITLE
add faster code for better performance.

### PR DESCRIPTION
**Pull request by Poltergeist**
According to http://jsperf.com/innerhtml-vs-removechild removeChild has a faster execution time (about a 100 times) then innerHTML.

### CODE REVIEW

**Comment by fbrandel** [comment]
According to the Catholic Church "removeChild" is not goot at all. Not sure if it should be implemented into ParisHilton.js by default.

**Comment by Poltergeist** [comment]
I am not talking about abortion I am talking about removing a child from a node in the Document Object Model. So the Catholic Church doesn't have any influence in what is important and what isn't or at least it shouldn't.

**Comment by Anachron** [comment]
I don't think it fits to ParisHilton.js; In my opinion that's not the main function of ParisHilton.js...

**Comment by Poltergeist** [comment]
It is the same function just in a more performant and cleaner style. In my opinion this belongs into parisHilton.js even if this is just a joke it can also be education to someone and I do think that a lot of people can learn of this little code snippet.

**Comment by Anachron** [comment]
Please don't try to change ParisHilton.js into something that it just isn't. Let it be what it wants to be, merge with what it wants to merge and publish whatever it wants to.

// my work here is done

**Pull request closed without merging**
